### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by sirzento** [danielgindi/jquery.dgtable#2]
Hey,

1. [ ] 1. Is it possible to set the column width to the width of the biggest cell in the column?

2. [x] [2. How can you add a class to specific rows? Each of my rows should have a class name similar to the Content of the "name" cell.
](https://github.com/danielgindi/jquery.dgtable/issues/2#issuecomment-403805457)
3. [x] [3. Is there a easy way to add a search Input under each header cell so its part of the Header and "sticky" too?](https://github.com/danielgindi/jquery.dgtable/issues/2#issuecomment-403808952)

    4. [x] [3.1. Search with multiple Inputs.](https://github.com/danielgindi/jquery.dgtable/issues/4)
<br>

5. [x] [4. How can I make the width of the table dynamic? If the window gets smaller, the table should be smaller too.](https://github.com/danielgindi/jquery.dgtable/issues/2#issuecomment-416924680)

    6. [ ] 4.1. The same Thing but with height.
<br>

7. [x] [5. Is it possible to change the row height of a virtual table? Not dynamic just that every row is twice as heigth than now.](https://github.com/danielgindi/jquery.dgtable/issues/2#issuecomment-416953578)

    8. [x] [5.1. Dynamic row height in virtual mode.](https://github.com/danielgindi/jquery.dgtable/issues/3)
<br>

9. [x] [6. Is there already a way to formate a date format? My current Format ist "YYYY-MM-DDTHH:mm:SS.ms"(The T is just the char T) but I want it like DD.MM.YYYY HH:mm:SS (Note: The date is only in a specific column)](https://github.com/danielgindi/jquery.dgtable/issues/2#issuecomment-416877097)

11. [ ] 7. The right side should [look like this](https://imgur.com/ZVqnnc9), but if I scroll to the left [this happens](https://imgur.com/WYlH8TM). Can you somehow prevent this?

12. [x] [8. The row Count gets updatet after each search but still has the value of all rows. I think it would be better if it matches with the count of the searched rows.](https://github.com/danielgindi/jquery.dgtable/issues/2#issuecomment-423431676)

____
This now looks like an FAQ :)

**Comment by yeya** [comment]
Answer for question 2 - check [the example](https://github.com/danielgindi/jquery.dgtable/blob/c072b758b739bee225b6f2e731e5738791bbcfcb/example/example.html#L348)
on `rowcreate` you can set the class by the `rowData`

**Comment by sirzento** [comment]
Perfect.

Do you know where I can change the row heigth?

**Comment by sirzento** [comment]
An bad attempt on 6. was this:

```Javascript 
cellFormatter: function (value, columnName, rowData) {
                        if (columnName == "LocalTime") {
                            var splitDateTime = value.split('T');
                            var splitDate = splitDateTime[0].split('-');
                            var splitTime = splitDateTime[1].split('.')[0];
                            value = splitDate[2] + "." + splitDate[1] + "." + splitDate[0] + " " + splitTime;
                        }
                        return value;                   
                        }
```
**This works but breaks the search.** 
If original value was "2018-05-03" it is shown as "03.05.2018" but if you want to search now the date, you must search for the old Format, even it is shown correctly.

**Comment by danielgindi** [comment]
1. I don't understand what you mean

4. Set the table's width to whatever you want in CSS, like 100%. You can see that in the example.
    As for the columns, there are different behaviors that you can control with these flags:
```
relativeWidthGrowsToFillWidth: Boolean=true When set, relative width columns automatically grow to fill the table's width.
relativeWidthShrinksToFillWidth: Boolean=false When set, relative width columns automatically shrink to fill the table's width.
autoFillTableWidth: Boolean=false When set, columns are stretched proportionally to fill the table width (only if there is space left). Will supersede relativeWidthGrowsToFillWidth in the future.
```

5. Of course. You can set whatever height you want. That's in the CSS.

6. You can set a formatter for any column you want. You might want to use *moment.js* to handle date formatting. As for searches - you have several options. A: Supply a custom filter function, and do filtering yourself. B: For each row in the dataset add a column for the formatted date (before supplying it to the table), and supply a custom comparator for the specific column - that redirects to the original column.

7. I can't really understand from those screenshots.

**Comment by sirzento** [comment]
Hey,
thanks for your answere.

At the first point I mean it like this:
You have a column named "Random_Data" and the length of the string are from 5 chars to 30 chars. Now the most string are 20 chars long but one is 30 chars long.
Now my question was it is possible to dynamicly set the wide of the column "Random_Data" exactly so that the longest string (30 chars) can be displayed perfectly?

5. What must I change for that? I already tried it and the rows are displayed right but if I scroll it gets very strange.

6. For a I think my knowledge is too little for that and B, you mean that I change my data before I pass it to the table? Thats not possible for me :/

7. I mean in the first screenshoot over the scrollbar is a little white squere fits perfectly in and the blue from the Header stops where the scrollbar would start. But if you scroll the Header gets more to the left. It would be perfect if the white space would stay there.Or it would be good too if the scrollbar just goes all the way up.


And is it possible to serach from more than one text field? To search in more than one column.

**Comment by sirzento** [comment]
For 8. I've been using "getRowCount()" instead of "getRowFilteredCount()" all this time. So thats the solution.

**Comment by danielgindi** [comment]
For 2 - I just got that the issue actually exists - sometimes. Fixed.
For 4.1 - You should use CSS for that, and let the table `render()` when something significant changes.

**Comment by danielgindi** [comment]
1 "Is it possible to set the column width to the width of the biggest cell in the column" - I did not understand this one...
